version: '3'

services:
 backend:
  build: ./backend
  ports:
   - 8080:8080
  environment:
   - REDIS_HOST=redis
   - POSTGRES_HOST=db
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  depends_on:
   - db

 frontend:
  build: ./frontend
  ports:
   - 5000:5000

 redis:
  image: "redis:alpine"
  volumes:
   - redis_data:/data
  ports:
   - 6379:6379

 db:
  image: "postgres:alpine"
  restart: always
  environment:
   POSTGRES_PASSWORD: postgres
  container_name: db_backend
  volumes:
   - ./database:/var/lib/postgresql/data
  ports:
   - 5432:5432

volumes:
 redis_data:
